---

- name: install mariadb
  yum: name={{item}} state=present
  with_items:
    - mariadb-server
    - mariadb-devel

- name: install mysql-python via pip
  pip: name={{item}} state=present
  with_items:
    - MySQL-python

- name: enable mariadb service
  service: name=mariadb state=started enabled=yes

- include: mysql_secure_installation.yml

- name: set mysql encoding to utf8
  copy: src=utf8-mysqld.cnf dest=/etc/my.cnf.d/utf8-mysqld.cnf
  notify:
    - restart mariadb
