---

- name: install mariadb
  yum: name={{item}} state=present
  with_items:
    - mariadb-server
    - mariadb-devel

- name: install mysql-python via pip
  pip: name={{item}} state=present
  with_items:
    - MySQL-python

- name: enable mariadb service
  service: name=mariadb state=started enabled=yes

- include: mysql_secure_installation.yml

- name: set mysql encoding to utf8
  copy: src=utf8-mysqld.cnf dest=/etc/my.cnf.d/utf8-mysqld.cnf
  notify:
    - restart mariadb

- name: create database {{mysql['database']}}
  mysql_db: name={{mysql['database']}} state=present

- name: create normal mysql user {{mysql['user_name']}}
  mysql_user: name={{mysql['user_name']}} state=present
              password={{mysql['user_password']}}
              priv=dian.*:ALL
              host=localhost

- name: copy user my.cnf file with {{user}} password credentials
  template: src="my.cnf.{{user}}.j2" dest="/home/{{user}}/.my.cnf"
             owner={{user}} group={{user}} mode=0600
