---

- name: pip install requirements in virtualenv
  pip: requirements={{projects_root_dir}}/dian-server/requirements.txt
       virtualenv={{projects_root_dir}}/dian-server/.venv

- name: configure dian-server
  template: src=dian-server/local_settings.py.j2
            dest={{projects_root_dir}}/dian-server/dian/local/local_settings.py
            owner={{user}} group={{group}} mode=0644

- name: run django manage.py collectstatic
  django_manage: command=collectstatic
                 app_path={{projects_root_dir}}/dian-server/dian/
                 settings=dian.settings
                 virtualenv={{projects_root_dir}}/dian-server/.venv

- name: run django manage.py syncdb
  django_manage: command=syncdb
                 app_path={{projects_root_dir}}/dian-server/dian/
                 settings=dian.settings
                 virtualenv={{projects_root_dir}}/dian-server/.venv

- name: run django manage.py migrate
  django_manage: command=migrate
                 app_path={{projects_root_dir}}/dian-server/dian/
                 settings=dian.settings
                 virtualenv={{projects_root_dir}}/dian-server/.venv

- name: run django manage.py createsuperuser
  django_manage: command="createsuperuser --noinput --username=admin"
                 app_path={{projects_root_dir}}/dian-server/dian/
                 settings=dian.settings
                 virtualenv={{projects_root_dir}}/dian-server/.venv
