---

- name: settings tmux.conf
  copy: src=nginx.repo dest=/etc/yum.repos.d/nginx.repo

- name: install nginx
  yum: name={{item}} state=present
  with_items:
    - nginx

- name: update nginx conf
  template: src=nginx.conf.j2 dest=/etc/nginx/conf.d/nginx.conf

# `git clone --depth=1` to improve speed
# - name: git clone multiple repos from diankuai
#   git: repo=https://github.com/diankuai/{{item}}
#        dest=/tmp/{{item}}
#        depth=1
#   with_items:
#     - dian-server
#     - dian-web
#     - dian-home
