---

- name: install rabbitmq-server
  yum: name={{item}} state=present
  with_items:
    - rabbitmq-server

- name: enable rabbitmq-server service
  service: name=rabbitmq-server state=started enabled=yes

- name: create a rabbitmq vhost
  rabbitmq_vhost: name={{rabbitmq_vhost}} state=present

- name: create a rabbitmq user and assign full access control
  rabbitmq_user: user={{rabbitmq_user}}
                 password={{rabbitmq_user_password}}
                 vhost={{rabbitmq_vhost}}
                 configure_priv=.*
                 read_priv=.*
                 write_priv=.*
                 state=present
