---

- name: install rabbitmq-server
  yum: name={{item}} state=present
  with_items:
    - rabbitmq-server

- name: enable rabbitmq-server service
  service: name=rabbitmq-server state=started enabled=yes
