---

- hosts: vagrant
  sudo: yes
  vars:
    user: dian
    group: dian
    projects_root_dir: /home/dian/diankuai
    whoami: "{{lookup('env','USER')}}"
    user_home: "{{lookup('env','HOME')}}"
    git:
      user_name: "Xiao Hanyu"
      user_email: "xiaohanyu1988@gmail.com"
      pull: no                  # Should `git pull` for existing git repo?
    mysql:
      root_password: "mysqlrootpass@2015"
      database: "dian"
      user_name: "dian"
      user_password: "mysqluserpass@2015"
      host: "localhost"
      port: "3306"
    rabbitmq:
      user_name: "dian"
      user_password: "rabbitmquserpass@2015"
      vhost: "/dian"
    role_common_done: false
  roles:
    - web
    - db
    - mq
