python dian/manage.py schemamigration --auto account
python dian/manage.py schemamigration --auto menu
python dian/manage.py schemamigration --auto registration
python dian/manage.py schemamigration --auto restaurant
python dian/manage.py schemamigration --auto table
python dian/manage.py schemamigration --auto trade
python dian/manage.py schemamigration --auto wechat
python dian/manage.py schemamigration --auto reward
python dian/manage.py schemamigration --auto game 
