python dian/manage.py schemamigration --initial account
python dian/manage.py schemamigration --initial menu
python dian/manage.py schemamigration --initial registration
python dian/manage.py schemamigration --initial restaurant
python dian/manage.py schemamigration --initial table
python dian/manage.py schemamigration --initial trade
python dian/manage.py schemamigration --initial wechat
python dian/manage.py schemamigration --initial reward
python dian/manage.py schemamigration --initial game
python dian/manage.py schemamigration --initial photo
python dian/manage.py schemamigration --initial message
